packages:
- .
- location: ../wlc-hs
  extra-dep: True
extra-deps:
- xkbcommon-0.0.1
- data-flags-0.0.3.1
- storable-record-0.0.3
- utility-ht-0.0.11
- emacs-keys-0.0.2.0
- mvc-1.1.0
resolver: lts-3.12
